# Development environment configuration
baseURL = 'http://localhost:1313/'

[params]
env = "development"
images = ["/opengraph.jpg"]

[params.assets]
favicon = "/logo.svg"
favicon16x16 = "/logo.svg"
favicon32x32 = "/logo.svg"
apple_touch_icon = "/logo.svg"
safari_pinned_tab = "/logo.svg"

