# Production environment configuration
baseURL = '/blog'

[params]
env = "production"
images = ["/blog/opengraph.jpg"]

[params.assets]
favicon = "/blog/logo.png"
favicon16x16 = "/blog/logo.png"
favicon32x32 = "/blog/logo.png"
apple_touch_icon = "/blog/logo.png"
safari_pinned_tab = "/blog/logo.png"

